# version: '3.4'
# services:
#     db:
#         container_name: banxso_db
#         image: postgres:15-alpine
#         environment:
#             POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
#             POSTGRES_DB: '${POSTGRES_DB}'
#             POSTGRES_USER: '${POSTGRES_USER}'
#         ports:
#             - '${POSTGRES_PORT}:5432'
#         healthcheck:
#             test:
#                 [
#                     'CMD-SHELL',
#                     'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}',
#                 ]
#             interval: 5s
#             timeout: 5s
#             retries: 5
#         networks:
#             - banxso-network
#     server:
#         container_name: banxso_server
#         env_file:
#             - .env
#         restart: 'no'
#         depends_on:
#             db:
#                 condition: service_healthy
#         ports:
#             - '${SERVER_PORT}:${SERVER_PORT}'
#         build:
#             context: .
#             dockerfile: ./Dockerfile.production
#         # volumes:
#         #     - ./src:/app/src
#         networks:
#             - banxso-network
# networks:
#     banxso-network:
#         driver: bridge
